@DotNetCoreWebApi_HostAddress = https://localhost:7020

### WeatherForecast - Get all
GET {{DotNetCoreWebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### VegProducts - Get all products
GET {{DotNetCoreWebApi_HostAddress}}/api/vegproducts
Accept: application/json

###

### VegProducts - Get product by ID
GET {{DotNetCoreWebApi_HostAddress}}/api/vegproducts/1
Accept: application/json

###

### VegProducts - Create new product
POST {{DotNetCoreWebApi_HostAddress}}/api/vegproducts
Content-Type: application/json

{
  "name": "Tomato",
  "description": "Fresh red tomatoes",
  "price": 2.50,
  "idCategory": 1
}

###

### VegProducts - Update product
PUT {{DotNetCoreWebApi_HostAddress}}/api/vegproducts/1
Content-Type: application/json

{
  "id": 1,
  "name": "Carrot",
  "description": "Organic carrots",
  "price": 3.00,
  "idCategory": 1
}

###

### VegProducts - Delete product
DELETE {{DotNetCoreWebApi_HostAddress}}/api/vegproducts/1

###

### VegCategories - Get all categories
GET {{DotNetCoreWebApi_HostAddress}}/api/vegcategories
Accept: application/json

###

### VegCategories - Create new category
POST {{DotNetCoreWebApi_HostAddress}}/api/vegcategories
Content-Type: application/json

{
  "categoryName": "Vegetables",
  "description": "Fresh vegetables"
}

###

### VegCategories - Update category
PUT {{DotNetCoreWebApi_HostAddress}}/api/vegcategories/1
Content-Type: application/json

{
  "idCategory": 1,
  "categoryName": "Organic Vegetables",
  "description": "Fresh organic vegetables",
  "createdAt": "2024-01-01T00:00:00"
}

###

### VegCategories - Delete category
DELETE {{DotNetCoreWebApi_HostAddress}}/api/vegcategories/1

###
