// <auto-generated />
using System;
using DotNetCoreWebApi.Application.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCoreWebApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260215220745_AddVegCategory")]
    partial class AddVegCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCoreWebApi.Application.Entities.VegCategory", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategory");

                    b.ToTable("VegCategories");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Application.Entities.VegProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("VegProducts");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Application.Entities.VegProducts", b =>
                {
                    b.HasOne("DotNetCoreWebApi.Application.Entities.VegCategory", "VegCategory")
                        .WithMany("VegProducts")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VegCategory");
                });

            modelBuilder.Entity("DotNetCoreWebApi.Application.Entities.VegCategory", b =>
                {
                    b.Navigation("VegProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
